urls.py
#coding: utf-8
from django.conf.urls.defaults import *
from settings import MEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from show.sitemap import ShowSitemap
sitemaps =  {
    "show": ShowSitemap,
}

urlpatterns = patterns('',
    # Example:
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
    url(r'^register/$', "person.views.register", name="regsiter"),
    (r'static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, "show_indexes": True}, ),
    (r'^$', 'show.views.show_new'),
    #(r'^$', 'show.views.index'),
    url(r'^settings/$', 'person.views.settings', name="settings"),
    url(r'^show/add/$', 'show.views.add_show', name="add_show"),
    url(r'^show/add_by_poster$', 'show.views.add_by_poster', name="show_add_by_poster"),
    url(r'^show/(?P<show_pk>\d+)/$', 'show.views.show', name="show"),
    url(r'^show/(?P<show_pk>\d+)/edit/$', 'show.views.edit_show', name="edit_show"),
    url(r'^show/(?P<show_pk>\d+)/comment/$', 'show.views.show', name="comment_show"),
    url(r'^show/user/(?P<user_pk>\d+)/$', 'show.views.show_user', name="show_user"),
    url(r'^show/user/$', 'show.views.show_user', name="show_my"),
    url(r'^show/user/(?P<user_pk>\d+)/likes/$', 'show.views.show_user_likes', name="show_user_likes"),
    url(r'^show/(?P<show_pk>\d+)/like/$', 'show.views.show_like', name="show_like"),
    url(r'^show/tag/(?P<tagname>.*)/$', 'show.views.show_tag', name="show_tag"),
    url(r'^show/tags/$', 'show.views.show_tags', name="show_tags"),
    url(r'^show/new/$', 'show.views.show_new', name="show_new"),
    url(r'^show/hot/$', 'show.views.show_hot', name="show_hot"),
    url(r'^show/sitemap/$', 'show.views.show_sitemap', name="show_sitemap"),
    url(r'^comment/add/$', 'commentit.views.add_comment', name="add_comment"),
    url(r'^comment/delete/(?P<comment_pk>\d+)$', 'commentit.views.delete_comment', name="delete_comment"),
    url(r'^person/following/(?P<user_pk>\d+)/$', 'person.views.following', name="following"),
    url(r'^person/following/(?P<user_pk>\d+)/undo/$', 'person.views.following', {"undo": True }, name="undo_following"),
    url(r'^person/follower/(?P<user_pk>\d+)/$', 'person.views.follower', name="follower"),
    url(r'^person/followee/(?P<user_pk>\d+)/$', 'person.views.followee', name="followee"),
    url(r'^person/password/change$', "person.views.password_change", name="password_change"),
    url(r'^captcha/', include('captcha.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

show/models.py
#coding: utf-8
import tagging
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from common.stdimage import StdImageField
from commentit.models import Comment
from django.forms.fields import URLField
from django.contrib.contenttypes.models import ContentType
from django.db.models import signals, F

class Show(models.Model):
    user = models.ForeignKey(User, verbose_name=u"帐号")
    title = models.CharField(max_length=100, verbose_name=u"标题")
    image = StdImageField(upload_to="show_photo", size=(800,600), thumbnail_size=(100,300), verbose_name=u"上传照片")
    image_url = models.URLField(blank=True, verbose_name=u"照片链接")
    description = models.TextField(max_length=256, blank=True, verbose_name=u"简短描述")
    quote = models.CharField(max_length=256, blank=True, verbose_name=u"引用")
    dtcreated = models.DateTimeField(db_index=True, auto_now_add=True, verbose_name=u"创建日期")
    is_valid = models.NullBooleanField(verbose_name=u"是否合法", blank=True, help_text=u"审核此帖子是否存在不良内容")

    hits = models.PositiveIntegerField(default=0, editable=False, verbose_name=u"采样数") 
    read_count = models.PositiveIntegerField(default=0, editable=False, verbose_name=u"浏览数") 
    like_count = models.PositiveIntegerField(default=0, editable=False, verbose_name=u"喜欢数")
    comment_count = models.PositiveIntegerField(default=0, editable=False, verbose_name=u"评论数")

    comments = generic.GenericRelation(Comment)
    likes = models.ManyToManyField(User, null=True, blank=True, verbose_name=u"喜欢者", related_name="likes")

    def __unicode__(self):
        return u"%s" % self.title

    @property
    def quote_url(self):
        url = URLField()
        try:
            return url.clean(self.quote)
        except:
            return None

    @property
    def content_type(self):
        content_type = ContentType.objects.get_for_model(self)
        return content_type

    @property
    def tags_string(self):
        return ",".join([t.name for t in self.tags])

    @property
    def likit(self):
        return self.actions.filter(action="like")

    @property
    def likit_user_pks(self):
        return self.likit.values_list("user", flat=True)

    @models.permalink
    def get_absolute_url(self):
        return ("show", [str(self.pk)])

    def save(self, *args, **kwargs):
        super(Show, self).save(*args, **kwargs)
        profile = self.user.get_profile()
        profile.like_count = self.user.likes.count()
        profile.show_count = self.user.show_set.count()

        profile.save()
        return self

    def delete(self, *args, **kwargs):
        super(Show, self).delete(*args, **kwargs)
        profile = self.user.get_profile()
        profile.like_count = self.user.likes.count()
        profile.show_count = self.user.show_set.count()
        profile.save()

    class Meta:
        ordering = ["-dtcreated"]

tagging.register(Show)

def increase_photo_comment_count(sender, instance, signal, **kwargs):
    if instance.content_type.model_class() == Show:
        photo = Show.objects.get(pk=instance.object_id)
        photo.comment_count = F("comment_count") + 1
        photo.save()

def decrease_photo_comment_count(sender, instance, signal, **kwargs):
    if instance.content_type.model_class() == Show:
        photo = Show.objects.get(pk=instance.object_id)
        photo.comment_count = F("comment_count") - 1
        photo.save()

models.signals.post_save.connect(increase_photo_comment_count, sender=Comment)
models.signals.post_delete.connect(decrease_photo_comment_count, sender=Comment)

class ShowImage(models.Model):
    show = models.ForeignKey("Show")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    image = StdImageField(null=True, upload_to="show_showimage", size=(800,600), thumbnail_size=(100,300), verbose_name=u"上传照片")
    image_url = models.URLField()
    description = models.TextField()

    def __unicode__(self):
        return self.description

def update_show_image_url(sender, instance, signal, **kwargs):
    if not instance.show.image and not instance.show.image_url:
        instance.show.image_url = instance.image_url
    elif instance.modified < instance.show.dtcreated:
        instance.show.image_url = instance.image_url
    instance.show.save()

models.signals.post_save.connect(update_show_image_url, sender=ShowImage)

show/forms.py
#coding: utf-8
from django import forms
from show.models import Show
from captcha.fields import CaptchaField

class ShowForm(forms.ModelForm):
    def clean(self):
        cleaned_data = self.cleaned_data
        image = cleaned_data.get("image")
        image_url = cleaned_data.get("image_url")
        if not image_url and not image:
            raise forms.ValidationError(u"上传照片")
        return cleaned_data

    class Meta:
        model = Show
        exclude = ("user", "read_count", "like_count", "comment_count", "likes" )

show/views.py
#coding: utf-8
import urllib2
import urllib
import json
import time
from person.models import Follow
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template import RequestContext
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from django.db.models import F
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from show.models import Show, ShowImage

# Create your views here.

def index(request):
    return HttpResponseRedirect(reverse("show_hot"))

    q = request.GET.get("q", "")
    page = int(request.GET.get("page", 1))

    show_list = Show.objects.all().order_by("-like_count", "-comment_count", "-dtcreated")
    if q:
        show_list = show_list.filter(title__icontains=q)

    query_string = request.META.get("QUERY_STRING", u"")
    query_part = query_string.split("&")
    new_query_parts = []
    for qp in query_part:
        if not qp.startswith("page="):
            new_query_parts.append(qp)
    no_page_query_string = u"&".join(new_query_parts)

    pages = Paginator(show_list, 5)
    pages.cur_page = pages.page(page)
    pages.page_prefix_link = request.path + "?"+ no_page_query_string
    return render_to_response("show/index.xhtml", locals(), context_instance=RequestContext(request))

def show_new(request):
    """最新的Show"""
    q = request.GET.get("q", "")
    page = int(request.GET.get("page", 1))

    show_list = Show.objects.filter(is_valid=True).order_by("-dtcreated", "-like_count", "-comment_count")
    #show_list = Show.objects.filter(is_valid=True).select_related().extra(
        #select = {
            ##"popularity": '(like_count - 1) / POW(TIMESTAMPDIFF(HOUR, dtcreated, CURRENT_TIMESTAMP()) + 2, 1.5)',
            ##如果不对like_count 强制数据类型转换, 由int型转为decimal， 当0 -1 的时候，得到的結果不是 -1 而是2^64 -1
            #"popularity": '(CAST(hits AS DECIMAL) - 1) / POW(TIMESTAMPDIFF(HOUR, dtcreated, CURRENT_TIMESTAMP()) + 2, 1.5)',
        #},
        #order_by = ['-popularity', "-hits", "-dtcreated"]
    #)
    if q:
        show_list = show_list.filter(title__icontains=q)

    query_string = request.META.get("QUERY_STRING", u"")
    query_part = query_string.split("&")
    new_query_parts = []
    for qp in query_part:
        if not qp.startswith("page="):
            new_query_parts.append(qp)
    no_page_query_string = u"&".join(new_query_parts)

    pages = Paginator(show_list, 10)
    pages.cur_page = pages.page(page)
    pages.page_prefix_link = request.path + "?"+ no_page_query_string
    return render_to_response("show/index.xhtml", locals(), context_instance=RequestContext(request))

def show_hot(request):
    """最热门的Show"""
    q = request.GET.get("q", "")
    page = int(request.GET.get("page", 1))

    #show_list = Show.objects.all().order_by("-like_count", "-comment_count", "-dtcreated")
    #流行度的计算参考如下链接
    #http://stackoverflow.com/questions/1965341/implementing-a-popularity-algorithm-in-django

    show_list = Show.objects.filter(is_valid=True).select_related().extra(
        select = {
            #"popularity": '(like_count - 1) / POW(TIMESTAMPDIFF(HOUR, dtcreated, CURRENT_TIMESTAMP()) + 2, 1.5)',
            #如果不对like_count 强制数据类型转换, 由int型转为decimal， 当0 -1 的时候，得到的結果不是 -1 而是2^64 -1
            "popularity": '(CAST(like_count AS DECIMAL) - 1) / POW(TIMESTAMPDIFF(HOUR, dtcreated, CURRENT_TIMESTAMP()) + 2, 1.5)',
        },
        order_by = ['-popularity', "-hits", "-dtcreated"]
    )
    if q:
        show_list = show_list.filter(title__icontains=q)

    query_string = request.META.get("QUERY_STRING", u"")
    query_part = query_string.split("&")
    new_query_parts = []
    for qp in query_part:
        if not qp.startswith("page="):
            new_query_parts.append(qp)
    no_page_query_string = u"&".join(new_query_parts)

    pages = Paginator(show_list, 10)
    pages.cur_page = pages.page(page)
    pages.page_prefix_link = request.path + "?"+ no_page_query_string
    return render_to_response("show/index.xhtml", locals(), context_instance=RequestContext(request))

def show_user(request, user_pk=None):
    """某个用户Show Space"""
    if user_pk is None:
        user = request.user
    else:
        user = get_object_or_404(User, pk=user_pk)

        profile = user.get_profile()
        profile.visit_count = F("visit_count") + 1
        profile.save()

    if request.user.is_authenticated():
        is_following = Follow.objects.filter(follower=request.user, followee=user).exists()
    else:
        is_following = False

    q = request.GET.get("q", "")
    page = int(request.GET.get("page", 1))

    show_list = user.show_set.all()
    if q:
        show_list = show_list.filter(title__icontains=q)

    query_string = request.META.get("QUERY_STRING", u"")
    query_part = query_string.split("&")
    new_query_parts = []
    for qp in query_part:
        if not qp.startswith("page="):
            new_query_parts.append(qp)
    no_page_query_string = u"&".join(new_query_parts)

    pages = Paginator(show_list, 10)
    pages.cur_page = pages.page(page)
    pages.page_prefix_link = request.path + "?"+ no_page_query_string
    return render_to_response("show/show_user.html", {
        "pages": pages,
        "show_user": user,
        "is_following": is_following,
    }, context_instance=RequestContext(request))

def show_user_likes(request, user_pk):
    """用户喜欢，收藏"""
    user = get_object_or_404(User, pk=user_pk)

    profile = user.get_profile()
    profile.visit_count = F("visit_count") + 1
    profile.save()

    if request.user.is_authenticated():
        is_following = Follow.objects.filter(follower=request.user, followee=user).exists()
    else:
        is_following = False

    q = request.GET.get("q", "")
    page = int(request.GET.get("page", 1))

    show_list = user.likes.all()
    if q:
        show_list = show_list.filter(title__icontains=q)

    query_string = request.META.get("QUERY_STRING", u"")
    query_part = query_string.split("&")
    new_query_parts = []
    for qp in query_part:
        if not qp.startswith("page="):
            new_query_parts.append(qp)
    no_page_query_string = u"&".join(new_query_parts)

    pages = Paginator(show_list, 10)
    pages.cur_page = pages.page(page)
    pages.page_prefix_link = request.path + "?"+ no_page_query_string
    return render_to_response("show/show_user_likes.html", {
        "pages": pages,
        "show_user": user,
        "is_following": is_following,
    }, context_instance=RequestContext(request))

@login_required
def add_show(request):
    """添加Show"""
    from show.forms import ShowForm 
    form = ShowForm(request.POST or None, request.FILES or None)
    #print form
    if form.is_valid():
        photo = form.save(commit=False)
        photo.user = request.user
        photo.save()
        photo.tags = request.POST.get("tags", None)
        #print photo
        return HttpResponseRedirect(reverse("show", args=[photo.pk]))
    return render_to_response("show/add-show.xhtml", locals(), context_instance=RequestContext(request))

@login_required
def edit_show(request, show_pk):
    """编辑Show"""
    from show.forms import ShowForm 
    photo = get_object_or_404(Show, pk=show_pk)
    if photo.user != request.user:
        return HttpResponseForbidden("Not Allow")
    form = ShowForm(request.POST or None, request.FILES or None, instance=photo)
    if form.is_valid():
        photo = form.save(commit=False)
        photo.user = request.user
        photo.save()
        photo.tags = request.POST.get("tags", None)
        return HttpResponseRedirect(reverse("show", args=[photo.pk]))
    return render_to_response("show/edit_show.html", locals(), context_instance=RequestContext(request))

def show(request, show_pk):
    """显示某个Show页面"""
    show = Show.objects.get(pk=show_pk)

    profile = show.user.get_profile()
    profile.visit_count = F("visit_count") + 1
    profile.save()

    show_session = "show" + show_pk
    if not request.session.get(show_session, False):
        request.session[show_session] = True
        show.read_count = F("read_count") + 1
        show.save()
        show = Show.objects.get(pk=show_pk)#reload the actual value after saved
    comments = show.comments.all()
    content_type = ContentType.objects.get_for_model(show)
    from commentit.forms import CommentForm
    form = CommentForm()
    return render_to_response("show/show.xhtml", locals(), context_instance=RequestContext(request))


def show_like(request, show_pk):
    """用户喜欢收藏某个Show"""
    if not request.user.is_authenticated():
        return HttpResponse(json.dumps({"success": False}))
    show = get_object_or_404(Show, pk=show_pk)
    undo = request.GET.get("undo", False)
    if undo:
        show.likes.remove(request.user)
    else:
        show.likes.add(request.user)
    show.like_count = show.likes.count()
    show.save()

    profile = request.user.get_profile()
    profile.like_count = request.user.likes.count()
    profile.save()

    res = {"success": True, "data": {"likit_count": show.likes.count()}, "undo": undo}
    return HttpResponse(json.dumps(res))


def show_tag(request, tagname):
    """显示某个Tagname的Show列表"""
    page = int(request.GET.get("page", 1))

    #show_list = Show.objects.all().order_by("-like_count", "-comment_count", "-dtcreated")
    #流行度的计算参考如下链接
    #http://stackoverflow.com/questions/1965341/implementing-a-popularity-algorithm-in-django
    from tagging.models import TaggedItem
    show_tag_list = TaggedItem.objects.get_by_model(Show, tagname)
    show_list = show_tag_list.filter(is_valid=True).select_related().extra(
        select = {
            #"popularity": '(like_count - 1) / POW(TIMESTAMPDIFF(HOUR, dtcreated, CURRENT_TIMESTAMP()) + 2, 1.5)',

templates/show/add_by_poster.html
{% extends "base/base.xhtml" %}
{% block content %}
<form id="addForm" method="post" enctype="multipart/form-data">
    <h5>+ 淘宝画报导入分享</h5>
    {% csrf_token %}
    <div class="formrow">
        <label for="id_quote">引用淘宝画报URL, 如http://huabao.taobao.com/fashion/d-256015.htm#poster-detail </label>
        <p><input type="text" id="taobao_huabao_url" name="taobao_huabao_url" class="longinput" /></p>
    </div>
    <p>
        <input type="submit" class="submit-button" value="提交，分享" />
    </p>
</form>
<style type="text/css">
#addForm {
    padding: 10px;
}
#addForm label {
    color: #888;
}
#addForm label.required {
    color: #000;
}
.formrow {
    padding: 5px 0;
}
#addForm h5 {
    margin-bottom: 10px;
}
#addForm p {
    padding: 5px 0;
}
.longinput {
    width: 100%;
    padding: 5px;
    border: 2px solid #eee;
}
.longinput:focus {
    border-color: #FF5C69;
    border-color: #888;
}
.submit-button {
    padding: 10px 20px;
}
.submit-button:hover {
    padding: 10px 20px;
}
ul.errorlist {
    color: #cc0066;
    padding: 10px;
    display: inline;
}
ul li {
    display: inline;
}

</style>
{% endblock %}

templates/show/edit_show.html
{% extends "base/base.xhtml" %}
{% block content %}
<form id="addForm" method="post" enctype="multipart/form-data">
    <h5>编辑分享</h5>
    {% if photo.image %}
    <img src="{{ photo.image.url }}" />
    {% else %}
    <img src="{{ photo.image_url }}" />
    {% endif %}
    {% csrf_token %}
    <div class="formrow">
        <label for="id_title" class="required">标题</label>{{ form.title.errors }}
        <p><input type="text" class="longinput" id="id_title" name="title" value="{{ photo.title }}" /></p>
    </div>
    <div class="formrow">
        <label for="id_image" class="required">上传照片(小于1M)</label>{{ form.image.errors }}
        <p><input type="file" id="id_image" class="longinput" name="image" /></p>
    </div>
    <div class="formrow">
        <label for="id_image_url" class="required">照片链接</label>{{ form.image_url.errors }}
        <p><input type="text" id="id_image_url" class="longinput" name="image" value="{{ photo.image_url }}" /></p>
    </div>
    <div class="formrow">
        <label for="id_description">简短描述(0 / 256个字)</label>{{ form.description.errors }}
        <p><textarea id="id_description" class="longinput" name="description">{{ photo.description }}</textarea></p>
    </div>
    <div class="formrow">
        <label for="id_tags">标签(多个标签间用<strong>英文逗号</strong>分开)</label>
        <p><input type="text" id="id_tags" class="longinput" name="tags" value="{{ photo.tags_string }}" /></p>
    </div>
    <div class="formrow">
        <label for="id_quote">引用</label>
        <p><input type="text" id="id_quote" name="quote" class="longinput" value="{{ photo.quote }}" /></p>
    </div>
    <p>
        <input type="submit" class="submit-button" value="更新，分享" />
    </p>
</form>
<style type="text/css">
#addForm {
    padding: 10px;
}
#addForm p label {
    color: #888;
    display: block;
    clear: both;
}
#addForm label.required {
    color: #000;
}
.formrow {
    padding: 5px 0;
}
#addForm h5 {
    margin-bottom: 10px;
}
#id_description {
    height: 70px;
}
#addForm p {
    padding: 5px 0;
}
#addForm input, #addForm textarea {
    width: 100%;
    padding: 5px;
    border: 2px solid #eee;
}
#addForm input.submit-button {
    width: auto;
    padding: 10px;
}
.longinput {
    width: 100%;
    padding: 5px;
    border: 2px solid #eee;
}
.longinput:focus {
    border-color: #FF5C69;
    border-color: #888;
}
.submit-button {
    padding: 10px 20px;
}
.submit-button:hover {
    padding: 10px 20px;
}
ul.errorlist {
    color: #cc0066;
    padding: 10px;
    display: inline;
}
ul li {
    display: inline;
}

</style>
{% endblock %}

templates/show/show_user.html
{% extends "base/base.xhtml" %}

{% block banner %}
{% endblock %}


{% block extra-head %}
<style type="text/css">
#show-user-profile {
    background-color: #f8f8f8;
    padding: 10px;
}
#avatar-wrapper {
    float: left;
    margin-right: 10px;
}
#avatar-wrapper img {
    width: 100px;
    height: 100px;
}
#user-info-wrapper p {
    padding-bottom: 5px;
}
#user-nickname {
    font-size: 2em;
    font-weight: bold;
}
#user-nav li {
    float: left;
    padding: 10px;
}
#user-nav {
    background: transparent url(/static/img/bg_gradient_grey.png) repeat-x center center;
    _background-image: none;
    _background-color: #eee;
    border-bottom: 1px solid #ddd;
    margin-bottom: 10px;
}
#user-nav li a.active {
    background-color: #fff;
    padding: 5px 10px 11px 10px;
    border: 1px solid #ddd;
    border-bottom: 0px;
    color: #FF5C69;
}
#admire {
    display: block;
    float: right;
    position: relative;
    margin-left: 400px;
    margin-bottom: -10px;
}
#add_show_notice {
    text-align: center;
    color: #000;
    margin-top: 50px;
}
</style>
{% endblock %}

{% block content %}

{% include "show/include/show_user_nav.html" %}

{% for s in pages.cur_page.object_list %}
<div class="show">
    <div class="show-header">
        {% if user in s.likes.all %}
        <a href="{% url show_like s.pk %}?undo=1" class="likit I_likit">我喜欢({{ s.likes.count }})</a>
        {% else %}
        <a href="{% url show_like s.pk %}" class="likit">我喜欢({{ s.likes.count }})</a>
        {% endif %}

        <a href="{% url show s.pk %}" class="show-title">{{ s.title }}</a>
        <p class="show-meta"><a href="#">{{ s.user }}</a> 
        分享于 {{ s.dtcreated }} <span class="read_count">浏览({{ s.read_count }})</span> <a href="{% url show s.pk %}">评论({{ s.comment_count }})</a> <a href="#">喜欢({{ s.like_count }})</a>
    </div>
    <div class="show-body">
        {% if s.image %}
        <a href="{% url show s.pk %}"><img src="{{ s.image.url }}" /></a>
        {% else %}
        <a href="{% url show s.pk %}"><img src="{{ s.image_url }}" /></a>
        {% endif %}
    </div>
</div>
{% empty %}
    {% if user == show_user %}
<p id="add_show_notice">你还没有同我们分享呢，现在要<a href="{% url add_show %}"><strong> + 分享</strong></a> 吗?</p>
    {% endif %}
{% endfor %}

<div id="paginator" class="clearfix">
    {% with pages.cur_page as page %}
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="previous">&laquo; 上一页</a>
    {% else %}
    <a class="disable">&laquo; 上一页</a>
    {% endif %}
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="next">下一页 &raquo;</a>
    {% else %}
    <a class="disable">&raquo; 下一页</a>
    {% endif %}
    {% endwith %}
</div><!--/paginator-->
<script type="text/javascript">
$(function () {
    $("a.likit").click(function (event) {
        event.preventDefault();
        var url = $(this).attr("href");
        var $obj = $(this);
        $.getJSON(url, function (res) {
            if(res.success) {
                if (res.undo) {
                    $obj.removeClass("I_likit");
                    $obj.attr("href", url.replace("undo=1", ""));
                } else {
                    $obj.addClass("I_likit");
                    $obj.attr("href", url + "undo=1");
                }
                $obj.html("我喜欢(" + res.data.likit_count + ")");
            } else {
                alert("你还没有注册或者登陆，无法收藏");
            }
        });
    });
});
</script>
{% endblock %}

templates/show/sitemap.html
{% extends "base/base.xhtml" %}
{% block content %}
{% for s in show_list %}
<div class="show">
    <a href="{% url show s.pk %}" class="show-title">{{ s.title }}</a>
    <p class="show-meta"><a href="{% url show_user s.user.pk %}">{{ s.user }}</a> 
    分享于 {{ s.dtcreated }} <span class="read_count">浏览({{ s.read_count }})</span> <a href="{% url show s.pk %}#commentsWrapper">评论({{ s.comment_count }})</a> <a href="{% url show s.pk %}#likes">喜欢({{ s.like_count }})</a>
    </p>
</div>
{% endfor %}

{% endblock %}

templates/show/tags.html
{% extends "base/base.xhtml" %}
{% block extra-head %}
<style type="text/css">
#tags {
    margin-bottom: 10px;
}
#tags li {
    padding: 5px;
    margin-bottom: 5px;
    display: inline;
}
a.tag {
    padding: 5px 0 5px 5px;
}
a.tag:hover {
    color: #FF5C69;
}
.tsize-0  {
    font-size: 13px;
}
.tsize-1 {
    font-size: 15px;
}
.tsize-2 {
    font-size: 20px;
}
.tsize-3 {
    font-size: 25px;
}
.tsize-4 {
    font-size: 30px;
}
.tsize-5 {
    font-size: 35px;
}
.tsize-6 {
    font-size: 40px;
}
</style>
{% endblock %}

{% block content %}
<div id="tags" class="clearfix">
    <ul>
        {% for t in pages.cur_page.object_list %}
        <li><a href="{% url show_tag t.name %}" class="tag"><span class="tsize-{{ t.level }}">{{ t.name }}</span></a></li>
        {% endfor %}
    </ul>
</div>

<div id="paginator" class="clearfix">
    {% with pages.cur_page as page %}
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="previous">&laquo; 上一页</a>
    {% else %}
    <a class="disable">&laquo; 上一页</a>
    {% endif %}
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="next">下一页 &raquo;</a>
    {% else %}
    <a class="disable">下一页 &raquo; </a>
    {% endif %}
    {% endwith %}
</div><!--/paginator-->
{% endblock %}